# Generated by Django 5.0.2 on 2024-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Mobiles'), ('FR', 'Formals'), ('TS', 'T-Shirts'), ('ST', 'Suits'), ('TP', 'Tops'), ('SR', 'Sarees'), ('KT', 'Kurtis')], max_length=2),
        ),
    ]
