# Generated by Django 5.0.2 on 2024-09-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'mobiles'), ('L', 'laptops'), ('MW', 'menswear'), ('WW', 'womenswear')], max_length=2),
        ),
    ]
