# Generated by Django 5.0.2 on 2024-09-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('COD', 'Cash on Delivery')], default='Razorpay', max_length=20),
        ),
    ]
